import React, { useEffect, useState } from 'react';
import { StyleSheet, Text, View, TouchableOpacity, ActivityIndicator, Alert, Platform } from 'react-native';
import * as RNIap from 'react-native-iap';

const itemSkus = Platform.select({
  android: ['bingo_weekly', 'bingo_monthly'],
  });

  export default function App() {
    const [loading, setLoading] = useState(false);
      const [subscriptions, setSubscriptions] = useState([]);

        useEffect(() => {
            let purchaseUpdateSubscription;
                let purchaseErrorSubscription;

                    const initIAP = async () => {
                          try {
                                  await RNIap.initConnection();
                                          if (Platform.OS === 'android') {
                                                    await RNIap.flushFailedPurchasesCachedAsPendingAndroid();
                                                            }
                                                                    const subs = await RNIap.getSubscriptions({ skus: itemSkus });
                                                                            setSubscriptions(subs);
                                                                                  } catch (err) {
                                                                                          console.warn('IAP Init Error:', err);
                                                                                                }
                                                                                                    };

                                                                                                        initIAP();

                                                                                                            purchaseUpdateSubscription = RNIap.purchaseUpdatedListener(async (purchase) => {
                                                                                                                  const receipt = purchase.transactionReceipt;
                                                                                                                        if (receipt) {
                                                                                                                                await RNIap.finishTransaction({ purchase, isConsumable: false });
                                                                                                                                        Alert.alert('Success', 'Subscription Activated!');
                                                                                                                                                setLoading(false);
                                                                                                                                                      }
                                                                                                                                                          });

                                                                                                                                                              purchaseErrorSubscription = RNIap.purchaseErrorListener((error) => {
                                                                                                                                                                    setLoading(false);
                                                                                                                                                                          if (error.code !== 'E_USER_CANCELLED') {
                                                                                                                                                                                  Alert.alert('Payment Failed', error.message || 'Unable to start payment.');
                                                                                                                                                                                        }
                                                                                                                                                                                            });

                                                                                                                                                                                                return () => {
                                                                                                                                                                                                      if (purchaseUpdateSubscription) purchaseUpdateSubscription.remove();
                                                                                                                                                                                                            if (purchaseErrorSubscription) purchaseErrorSubscription.remove();
                                                                                                                                                                                                                  RNIap.endConnection();
                                                                                                                                                                                                                      };
                                                                                                                                                                                                                        }, []);

                                                                                                                                                                                                                          const handleSubscribe = async (skuItem) => {
                                                                                                                                                                                                                              setLoading(true);
                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                        const offerToken = skuItem?.subscriptionOfferDetails?.[0]?.offerToken;

                                                                                                                                                                                                                                              if (!offerToken) {
                                                                                                                                                                                                                                                      Alert.alert('Error', 'No valid offerToken found for this subscription.');
                                                                                                                                                                                                                                                              setLoading(false);
                                                                                                                                                                                                                                                                      return;
                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                  await RNIap.requestSubscription({
                                                                                                                                                                                                                                                                                          sku: skuItem.productId,
                                                                                                                                                                                                                                                                                                  subscriptionOffers: [{ sku: skuItem.productId, offerToken }],
                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                                                                                                                                  setLoading(false);
                                                                                                                                                                                                                                                                                                                        Alert.alert('Error', err.message);
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                    <View style={styles.container}>
                                                                                                                                                                                                                                                                                                                                          <Text style={styles.title}>Bingo Premium Pass</Text>
                                                                                                                                                                                                                                                                                                                                                <Text style={styles.subtitle}>Unlock unlimited tickets and ad-free play!</Text>

                                                                                                                                                                                                                                                                                                                                                      {loading ? (
                                                                                                                                                                                                                                                                                                                                                              <ActivityIndicator size="large" color="#FFD700" />
                                                                                                                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                                                                                                            subscriptions.map((item) => (
                                                                                                                                                                                                                                                                                                                                                                                      <TouchableOpacity 
                                                                                                                                                                                                                                                                                                                                                                                                  key={item.productId} 
                                                                                                                                                                                                                                                                                                                                                                                                              style={styles.button} 
                                                                                                                                                                                                                                                                                                                                                                                                                          onPress={() => handleSubscribe(item)}
                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                <Text style={styles.buttonText}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              Subscribe ({item.productId.includes('weekly') ? 'Weekly' : 'Monthly'})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          container: { flex: 1, backgroundColor: '#121212', alignItems: 'center', justifyContent: 'center', padding: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            title: { fontSize: 26, fontWeight: 'bold', color: '#FFF', marginBottom: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              subtitle: { fontSize: 14, color: '#AAA', textAlign: 'center', marginBottom: 30 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                button: { backgroundColor: '#FFD700', paddingVertical: 15, paddingHorizontal: 30, borderRadius: 25, marginVertical: 10, width: '80%', alignItems: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  buttonText: { fontSize: 16, fontWeight: 'bold', color: '#000' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  